version: '3.0'

services:
   mongodb:
        image: mongo:latest
        container_name: my-mongo-container
        restart: always
        volumes:
          - ~/data/docker/mongodb:/data/db
        ports:
            - 27017:27017
        networks:
          - mydockernetwork
   eventsService:
     image: nicolanardino/events_service:1.0
     container_name: events-service
     depends_on:
       - mongodb
     links:
       - mongodb
     restart: always
     ports:
       - "9094:9094"
     networks:
          - mydockernetwork